biblename = "Burmese Bible, 1840";
metadata = [{
abbr:"Metadata",
short:"Metadata",
long:"Metadata",
osis:"x-Meta",
type:"meta",
nt:false,
chapters:1
},{
abbr:"Gen",
short:"ကမာၻဦးက်မ္း",
long:"ကမာၻဦးက်မ္း",
osis:"Gen",
type:"ot",
nt:false,
chapters:50
},{
abbr:"Exo",
short:"ထြက္ေျမာက္ရာက်မ္း",
long:"ထြက္ေျမာက္ရာက်မ္း",
osis:"Exod",
type:"ot",
nt:false,
chapters:40
},{
abbr:"Lev",
short:"၀တ္ျပဳရာက်မ္း",
long:"၀တ္ျပဳရာက်မ္း",
osis:"Lev",
type:"ot",
nt:false,
chapters:27
},{
abbr:"Num",
short:"ေတာလည္ရာက်မ္း",
long:"ေတာလည္ရာက်မ္း",
osis:"Num",
type:"ot",
nt:false,
chapters:36
},{
abbr:"Deu",
short:"တရားေဟာရာက်မ္း",
long:"တရားေဟာရာက်မ္း",
osis:"Deut",
type:"ot",
nt:false,
chapters:34
},{
abbr:"Josh",
short:"ေယာရွဳမွတ္စာ",
long:"ေယာရွဳမွတ္စာ",
osis:"Josh",
type:"ot",
nt:false,
chapters:24
},{
abbr:"Judg",
short:"တရားသူၾကီးမွတ္စာ",
long:"တရားသူၾကီးမွတ္စာ",
osis:"Judg",
type:"ot",
nt:false,
chapters:21
},{
abbr:"Ruth",
short:"ရုသ၀တၱဳ",
long:"ရုသ၀တၱဳ",
osis:"Ruth",
type:"ot",
nt:false,
chapters:4
},{
abbr:"1Sam",
short:"ဓမၼရာဇဝင္ပဌမေစာင္",
long:"ဓမၼရာဇဝင္ပဌမေစာင္",
osis:"1Sam",
type:"ot",
nt:false,
chapters:31
},{
abbr:"2Sam",
short:"ဓမၼရာဇဝင္ဒုတိယေစာင္",
long:"ဓမၼရာဇဝင္ဒုတိယေစာင္",
osis:"2Sam",
type:"ot",
nt:false,
chapters:24
},{
abbr:"1Kin",
short:"ဓမၼရာဇဝင္ တတိယေစာင္",
long:"ဓမၼရာဇဝင္ တတိယေစာင္",
osis:"1Kgs",
type:"ot",
nt:false,
chapters:22
},{
abbr:"2Kin",
short:"ဓမၼရာဇဝင္စတုတၳေစာင္",
long:"ဓမၼရာဇဝင္စတုတၳေစာင္",
osis:"2Kgs",
type:"ot",
nt:false,
chapters:25
},{
abbr:"1Chr",
short:"ရာဇဝင္ခ်ဳပ္ပဌမေစာင္",
long:"ရာဇဝင္ခ်ဳပ္ပဌမေစာင္",
osis:"1Chr",
type:"ot",
nt:false,
chapters:29
},{
abbr:"2Chr",
short:"ရာဇဝင္ခ်ဳပ္ဒုတိယေစာင္",
long:"ရာဇဝင္ခ်ဳပ္ဒုတိယေစာင္",
osis:"2Chr",
type:"ot",
nt:false,
chapters:36
},{
abbr:"Ezr",
short:"ဧဇရမွတ္စာ",
long:"ဧဇရမွတ္စာ",
osis:"Ezra",
type:"ot",
nt:false,
chapters:10
},{
abbr:"Neh",
short:"ေနဟမိမွတ္စာ",
long:"ေနဟမိမွတ္စာ",
osis:"Neh",
type:"ot",
nt:false,
chapters:13
},{
abbr:"Esth",
short:"ဧသတာဝတၱဳ",
long:"ဧသတာဝတၱဳ",
osis:"Esth",
type:"ot",
nt:false,
chapters:10
},{
abbr:"Job",
short:"ေယာဘဝတၱဳ",
long:"ေယာဘဝတၱဳ",
osis:"Job",
type:"ot",
nt:false,
chapters:42
},{
abbr:"Ps",
short:"ဆာလံက်မ္း",
long:"ဆာလံက်မ္း",
osis:"Ps",
type:"ot",
nt:false,
chapters:150
},{
abbr:"Prov",
short:"သုတၱံက်မ္း",
long:"သုတၱံက်မ္း",
osis:"Prov",
type:"ot",
nt:false,
chapters:31
},{
abbr:"Eccl",
short:"ေဒသနာက်မ္း",
long:"ေဒသနာက်မ္း",
osis:"Eccl",
type:"ot",
nt:false,
chapters:12
},{
abbr:"Song",
short:"ေရွာလမုန္သီခ်င္း",
long:"ေရွာလမုန္သီခ်င္း",
osis:"Song",
type:"ot",
nt:false,
chapters:8
},{
abbr:"Isa",
short:"ေဟရွာယအနာဂတိၱက်မ္း",
long:"ေဟရွာယအနာဂတိၱက်မ္း",
osis:"Isa",
type:"ot",
nt:false,
chapters:66
},{
abbr:"Jer",
short:"ေယရမိအနာဂတၱိက်မ္း",
long:"ေယရမိအနာဂတၱိက်မ္း",
osis:"Jer",
type:"ot",
nt:false,
chapters:52
},{
abbr:"Lam",
short:"ေယရမိျမည္တမ္းစကား",
long:"ေယရမိျမည္တမ္းစကား",
osis:"Lam",
type:"ot",
nt:false,
chapters:5
},{
abbr:"Ezek",
short:"ေယဇေက်လအနာဂတၱိက်မ္း",
long:"ေယဇေက်လအနာဂတၱိက်မ္း",
osis:"Ezek",
type:"ot",
nt:false,
chapters:48
},{
abbr:"Dan",
short:"ဒံေယလအနာဂတၱိက်မ္း",
long:"ဒံေယလအနာဂတၱိက်မ္း",
osis:"Dan",
type:"ot",
nt:false,
chapters:12
},{
abbr:"Hos",
short:"ေဟာေရွအနာဂတၱိက်မ္း",
long:"ေဟာေရွအနာဂတၱိက်မ္း",
osis:"Hos",
type:"ot",
nt:false,
chapters:14
},{
abbr:"Joel",
short:"ေယာလအနာဂတၱိက်မ္း",
long:"ေယာလအနာဂတၱိက်မ္း",
osis:"Joel",
type:"ot",
nt:false,
chapters:3
},{
abbr:"Am",
short:"အာမုတ္အနာဂတၱိက်မ္း",
long:"အာမုတ္အနာဂတၱိက်မ္း",
osis:"Amos",
type:"ot",
nt:false,
chapters:9
},{
abbr:"Oba",
short:"ၾသဗဒိဗ်ာဒိတ္ရူပါရုံ",
long:"ၾသဗဒိဗ်ာဒိတ္ရူပါရုံ",
osis:"Obad",
type:"ot",
nt:false,
chapters:1
},{
abbr:"Jona",
short:"ေယာနဝတၳဳ",
long:"ေယာနဝတၳဳ",
osis:"Jonah",
type:"ot",
nt:false,
chapters:4
},{
abbr:"Mic",
short:"မိကၡာအနာဂတၱိက်မ္း",
long:"မိကၡာအနာဂတၱိက်မ္း",
osis:"Mic",
type:"ot",
nt:false,
chapters:7
},{
abbr:"Nah",
short:"နာဟံုအနာဂတၱိက်မ္း",
long:"နာဟံုအနာဂတၱိက်မ္း",
osis:"Nah",
type:"ot",
nt:false,
chapters:3
},{
abbr:"Hab",
short:"ဟဗကၠဳတ္အနာဂတၱိက်မ္း",
long:"ဟဗကၠဳတ္အနာဂတၱိက်မ္း",
osis:"Hab",
type:"ot",
nt:false,
chapters:3
},{
abbr:"Zeph",
short:"ေဇဖနိအနာဂတၱိက်မ္း",
long:"ေဇဖနိအနာဂတၱိက်မ္း",
osis:"Zeph",
type:"ot",
nt:false,
chapters:3
},{
abbr:"Hag",
short:"ဟဂၢဲအနာဂတၱိက်မ္း",
long:"ဟဂၢဲအနာဂတၱိက်မ္း",
osis:"Hag",
type:"ot",
nt:false,
chapters:2
},{
abbr:"Zech",
short:"ဇာခရိအနာဂတၱိက်မ္း",
long:"ဇာခရိအနာဂတၱိက်မ္း",
osis:"Zech",
type:"ot",
nt:false,
chapters:14
},{
abbr:"Mal",
short:"မာလခိအနာဂတၱိက်မ္း",
long:"မာလခိအနာဂတၱိက်မ္း",
osis:"Mal",
type:"ot",
nt:false,
chapters:4
},{
abbr:"Mat",
short:"ရ္ဟင္မသ္သဲခရစ္ဝင္",
long:"ရ္ဟင္မသ္သဲခရစ္ဝင္",
osis:"Matt",
type:"nt",
nt:true,
chapters:28
},{
abbr:"Mar",
short:"ရ္ဟင္မာကုခရစ္ဝင္",
long:"ရ္ဟင္မာကုခရစ္ဝင္",
osis:"Mark",
type:"nt",
nt:true,
chapters:16
},{
abbr:"Luk",
short:"ရ္ဟင္လုကာခရစ္ဝင္",
long:"ရ္ဟင္လုကာခရစ္ဝင္",
osis:"Luke",
type:"nt",
nt:true,
chapters:24
},{
abbr:"John",
short:"ရ္ဟင္ယောဟန္ခရစ္ဝင္",
long:"ရ္ဟင္ယောဟန္ခရစ္ဝင္",
osis:"John",
type:"nt",
nt:true,
chapters:21
},{
abbr:"Acts",
short:"တမန္တော္ဝထ္ထု",
long:"တမန္တော္ဝထ္ထု",
osis:"Acts",
type:"nt",
nt:true,
chapters:28
},{
abbr:"Rom",
short:"ရောမဩဝာဒစာ",
long:"ရောမဩဝာဒစာ",
osis:"Rom",
type:"nt",
nt:true,
chapters:16
},{
abbr:"1Cor",
short:"ကောရိနသုဩဝာဒစာပဌမစောင္",
long:"ကောရိနသုဩဝာဒစာပဌမစောင္",
osis:"1Cor",
type:"nt",
nt:true,
chapters:16
},{
abbr:"2Cor",
short:"ကောရိနသုဩဝာဒစာဒုတိယစောင္",
long:"ကောရိနသုဩဝာဒစာဒုတိယစောင္",
osis:"2Cor",
type:"nt",
nt:true,
chapters:13
},{
abbr:"Gal",
short:"ဂလာတိဩဝာဒစာ",
long:"ဂလာတိဩဝာဒစာ",
osis:"Gal",
type:"nt",
nt:true,
chapters:6
},{
abbr:"Eph",
short:"ဧဖက္ဩဝာဒစာ",
long:"ဧဖက္ဩဝာဒစာ",
osis:"Eph",
type:"nt",
nt:true,
chapters:6
},{
abbr:"Phil",
short:"ဖိလိပ္ပိဩဝာဒစာ",
long:"ဖိလိပ္ပိဩဝာဒစာ",
osis:"Phil",
type:"nt",
nt:true,
chapters:4
},{
abbr:"Col",
short:"ကောလောသဲဩဝာဒစာ",
long:"ကောလောသဲဩဝာဒစာ",
osis:"Col",
type:"nt",
nt:true,
chapters:4
},{
abbr:"1Ths",
short:"သက္သာလောနိတ္ဩဝာဒစာပဌမစောင္",
long:"သက္သာလောနိတ္ဩဝာဒစာပဌမစောင္",
osis:"1Thess",
type:"nt",
nt:true,
chapters:5
},{
abbr:"2Ths",
short:"သက္သာလောနိတ္ဩဝာဒစာဒုတိယစောင္",
long:"သက္သာလောနိတ္ဩဝာဒစာဒုတိယစောင္",
osis:"2Thess",
type:"nt",
nt:true,
chapters:3
},{
abbr:"1Tim",
short:"တိမောသေဩဝာဒစာပဌမစောင္",
long:"တိမောသေဩဝာဒစာပဌမစောင္",
osis:"1Tim",
type:"nt",
nt:true,
chapters:6
},{
abbr:"2Tim",
short:"တိမောသေဩဝာဒစာဒုတိယစောင္",
long:"တိမောသေဩဝာဒစာဒုတိယစောင္",
osis:"2Tim",
type:"nt",
nt:true,
chapters:4
},{
abbr:"Tit",
short:"တိတုဩဝာဒစာ",
long:"တိတုဩဝာဒစာ",
osis:"Titus",
type:"nt",
nt:true,
chapters:3
},{
abbr:"Phlm",
short:"ဖိလေမုန္ဩဝာဒစာ",
long:"ဖိလေမုန္ဩဝာဒစာ",
osis:"Phlm",
type:"nt",
nt:true,
chapters:1
},{
abbr:"Heb",
short:"ဟေဗ္ရဲဩဝာဒစာ",
long:"ဟေဗ္ရဲဩဝာဒစာ",
osis:"Heb",
type:"nt",
nt:true,
chapters:13
},{
abbr:"Jam",
short:"ရ္ဟင္ယာကုပ္ဩဝာဒစာ",
long:"ရ္ဟင္ယာကုပ္ဩဝာဒစာ",
osis:"Jas",
type:"nt",
nt:true,
chapters:5
},{
abbr:"1Pet",
short:"ရ္ဟင္ပေတရုဩဝာဒစာပဌမစောင္",
long:"ရ္ဟင္ပေတရုဩဝာဒစာပဌမစောင္",
osis:"1Pet",
type:"nt",
nt:true,
chapters:5
},{
abbr:"2Pet",
short:"ရ္ဟင္ပေတရုဩဝာဒစာဒုတိယစောင္",
long:"ရ္ဟင္ပေတရုဩဝာဒစာဒုတိယစောင္",
osis:"2Pet",
type:"nt",
nt:true,
chapters:3
},{
abbr:"1Jn",
short:"ရ္ဟင္ယောဟန္ဩဝာဒစာပဌမစောင္",
long:"ရ္ဟင္ယောဟန္ဩဝာဒစာပဌမစောင္",
osis:"1John",
type:"nt",
nt:true,
chapters:5
},{
abbr:"2Jn",
short:"ရ္ဟင္ယောဟန္ဩဝာဒစာဒုတိယစောင္",
long:"ရ္ဟင္ယောဟန္ဩဝာဒစာဒုတိယစောင္",
osis:"2John",
type:"nt",
nt:true,
chapters:1
},{
abbr:"3Jn",
short:"ရ္ဟင္ယောဟန္ဩဝာဒစာတတိယစောင္",
long:"ရ္ဟင္ယောဟန္ဩဝာဒစာတတိယစောင္",
osis:"3John",
type:"nt",
nt:true,
chapters:1
},{
abbr:"Jud",
short:"ရ္ဟင္ယုဒဩဝာဒစာ",
long:"ရ္ဟင္ယုဒဩဝာဒစာ",
osis:"Jude",
type:"nt",
nt:true,
chapters:1
},{
abbr:"Rev",
short:"ဗ္ယာဒိတ္က္ယမ္း",
long:"ဗ္ယာဒိတ္က္ယမ္း",
osis:"Rev",
type:"nt",
nt:true,
chapters:22
}];
