biblename = "Myanmar Standard Bible";
metadata = [{
abbr:"Metadata",
short:"Metadata",
long:"Metadata",
osis:"x-Meta",
type:"meta",
nt:false,
chapters:1
},{
abbr:"Intro",
short:"_Introduction_",
long:"_Introduction_",
osis:"x-Intr",
type:"meta",
nt:false,
chapters:1
},{
abbr:"Ps",
short:"ဆာ​လံ​ကျမ်း",
long:"ဆာ​လံ​ကျမ်း",
osis:"Ps",
type:"ot",
nt:false,
chapters:150
},{
abbr:"Prov",
short:"သုတ္တံ​ကျမ်း",
long:"သုတ္တံ​ကျမ်း",
osis:"Prov",
type:"ot",
nt:false,
chapters:31
},{
abbr:"Eccl",
short:"ဒေ​သ​နာ​ကျမ်း",
long:"ဒေ​သ​နာ​ကျမ်း",
osis:"Eccl",
type:"ot",
nt:false,
chapters:12
},{
abbr:"Matt",
short:"ရှင်​မဿဲ​ခ​ရစ်​ဝင်",
long:"ရှင်​မဿဲ​ခ​ရစ်​ဝင်",
osis:"Matt",
type:"nt",
nt:true,
chapters:28
},{
abbr:"Mark",
short:"ရှင်​မာ​ကု​ခ​ရစ်​ဝင်",
long:"ရှင်​မာ​ကု​ခ​ရစ်​ဝင်",
osis:"Mark",
type:"nt",
nt:true,
chapters:16
},{
abbr:"Luke",
short:"ရှင်​လု​ကာ​ခ​ရစ်​ဝင်",
long:"ရှင်​လု​ကာ​ခ​ရစ်​ဝင်",
osis:"Luke",
type:"nt",
nt:true,
chapters:24
},{
abbr:"John",
short:"ရှင်​ယော​ဟန်​ခ​ရစ်​ဝင်",
long:"ရှင်​ယော​ဟန်​ခ​ရစ်​ဝင်",
osis:"John",
type:"nt",
nt:true,
chapters:21
},{
abbr:"Acts",
short:"တ​မန်​တော်​ဝတ္ထု",
long:"တ​မန်​တော်​ဝတ္ထု",
osis:"Acts",
type:"nt",
nt:true,
chapters:28
},{
abbr:"Rom",
short:"ရော​မ​ဩ​ဝါ​ဒ​စာ",
long:"ရော​မ​ဩ​ဝါ​ဒ​စာ",
osis:"Rom",
type:"nt",
nt:true,
chapters:16
},{
abbr:"1Cor",
short:"ကော​ရိန္သု​ဩ​ဝါ​ဒ​စာ​ပ​ထ​မ​စောင်",
long:"ကော​ရိန္သု​ဩ​ဝါ​ဒ​စာ​ပ​ထ​မ​စောင်",
osis:"1Cor",
type:"nt",
nt:true,
chapters:16
},{
abbr:"2Cor",
short:"ကော​ရိန္သု​ဩ​ဝါ​ဒ​စာ​ဒု​တိ​ယ​စောင်",
long:"ကော​ရိန္သု​ဩ​ဝါ​ဒ​စာ​ဒု​တိ​ယ​စောင်",
osis:"2Cor",
type:"nt",
nt:true,
chapters:13
},{
abbr:"Gal",
short:"ဂ​လာ​တိ​ဩ​ဝါ​ဒ​စာ",
long:"ဂ​လာ​တိ​ဩ​ဝါ​ဒ​စာ",
osis:"Gal",
type:"nt",
nt:true,
chapters:6
},{
abbr:"Eph",
short:"ဧ​ဖက်​ဩ​ဝါ​ဒ​စာ",
long:"ဧ​ဖက်​ဩ​ဝါ​ဒ​စာ",
osis:"Eph",
type:"nt",
nt:true,
chapters:6
},{
abbr:"Phil",
short:"ဖိ​လိပ္ပိ​ဩ​ဝါ​ဒ​စာ",
long:"ဖိ​လိပ္ပိ​ဩ​ဝါ​ဒ​စာ",
osis:"Phil",
type:"nt",
nt:true,
chapters:4
},{
abbr:"Col",
short:"ကော​လော​သဲ​ဩ​ဝါ​ဒ​စာ",
long:"ကော​လော​သဲ​ဩ​ဝါ​ဒ​စာ",
osis:"Col",
type:"nt",
nt:true,
chapters:4
},{
abbr:"1Thess",
short:"သက်​သာ​လော​နိတ်​ဩ​ဝါ​ဒ​စာ​ပ​ထ​မ​စောင်",
long:"သက်​သာ​လော​နိတ်​ဩ​ဝါ​ဒ​စာ​ပ​ထ​မ​စောင်",
osis:"1Thess",
type:"nt",
nt:true,
chapters:5
},{
abbr:"2Thess",
short:"သက်​သာ​လော​နိတ်​ဩ​ဝါ​ဒ​စာ​ဒု​တိ​ယ​စောင်",
long:"သက်​သာ​လော​နိတ်​ဩ​ဝါ​ဒ​စာ​ဒု​တိ​ယ​စောင်",
osis:"2Thess",
type:"nt",
nt:true,
chapters:3
},{
abbr:"1Tim",
short:"တိ​မော​သေ​ဩ​ဝါ​ဒ​စာ​ပ​ထ​မ​စောင်",
long:"တိ​မော​သေ​ဩ​ဝါ​ဒ​စာ​ပ​ထ​မ​စောင်",
osis:"1Tim",
type:"nt",
nt:true,
chapters:6
},{
abbr:"2Tim",
short:"တိ​မော​သေ​ဩ​ဝါ​ဒ​စာ​ဒု​တိ​ယ​စောင်",
long:"တိ​မော​သေ​ဩ​ဝါ​ဒ​စာ​ဒု​တိ​ယ​စောင်",
osis:"2Tim",
type:"nt",
nt:true,
chapters:4
},{
abbr:"Titus",
short:"တိ​တု​ဩ​ဝါ​ဒ​စာ",
long:"တိ​တု​ဩ​ဝါ​ဒ​စာ",
osis:"Titus",
type:"nt",
nt:true,
chapters:3
},{
abbr:"Phlm",
short:"ဖိ​လေ​မုန်​ဩ​ဝါ​ဒ​စာ",
long:"ဖိ​လေ​မုန်​ဩ​ဝါ​ဒ​စာ",
osis:"Phlm",
type:"nt",
nt:true,
chapters:1
},{
abbr:"Heb",
short:"ဟေ​ဗြဲ​ဩ​ဝါ​ဒ​စာ",
long:"ဟေ​ဗြဲ​ဩ​ဝါ​ဒ​စာ",
osis:"Heb",
type:"nt",
nt:true,
chapters:13
},{
abbr:"Jas",
short:"ရှင်​ယာ​ကုပ်​ဩ​ဝါ​ဒ​စာ",
long:"ရှင်​ယာ​ကုပ်​ဩ​ဝါ​ဒ​စာ",
osis:"Jas",
type:"nt",
nt:true,
chapters:5
},{
abbr:"1Pet",
short:"ရှင်​ပေ​တ​ရု​ဩ​ဝါ​ဒ​စာ​ပ​ထ​မ​စောင်",
long:"ရှင်​ပေ​တ​ရု​ဩ​ဝါ​ဒ​စာ​ပ​ထ​မ​စောင်",
osis:"1Pet",
type:"nt",
nt:true,
chapters:5
},{
abbr:"2Pet",
short:"ရှင်​ပေ​တ​ရု​ဩ​ဝါ​ဒ​စာ​ဒု​တိ​ယ​စောင်",
long:"ရှင်​ပေ​တ​ရု​ဩ​ဝါ​ဒ​စာ​ဒု​တိ​ယ​စောင်",
osis:"2Pet",
type:"nt",
nt:true,
chapters:3
},{
abbr:"1John",
short:"ရှင်​ယော​ဟန်​ဩ​ဝါ​ဒ​စာ​ပ​ထ​မ​စောင်",
long:"ရှင်​ယော​ဟန်​ဩ​ဝါ​ဒ​စာ​ပ​ထ​မ​စောင်",
osis:"1John",
type:"nt",
nt:true,
chapters:5
},{
abbr:"2John",
short:"ရှင်​ယော​ဟန်​ဩ​ဝါ​ဒ​စာ​ဒု​တိ​ယ​စောင်",
long:"ရှင်​ယော​ဟန်​ဩ​ဝါ​ဒ​စာ​ဒု​တိ​ယ​စောင်",
osis:"2John",
type:"nt",
nt:true,
chapters:1
},{
abbr:"3John",
short:"ရှင်​ယော​ဟန်​ဩ​ဝါ​ဒ​စာ​တ​တိ​ယ​စောင်",
long:"ရှင်​ယော​ဟန်​ဩ​ဝါ​ဒ​စာ​တ​တိ​ယ​စောင်",
osis:"3John",
type:"nt",
nt:true,
chapters:1
},{
abbr:"Jude",
short:"ရှင်​ယု​ဒ​ဩ​ဝါ​ဒ​စာ",
long:"ရှင်​ယု​ဒ​ဩ​ဝါ​ဒ​စာ",
osis:"Jude",
type:"nt",
nt:true,
chapters:1
},{
abbr:"Rev",
short:"ဗျာ​ဒိတ်​ကျမ်း",
long:"ဗျာ​ဒိတ်​ကျမ်း",
osis:"Rev",
type:"nt",
nt:true,
chapters:22
}];
