biblename = "Garrad Bible";
metadata = [{
abbr:"Metadata",
short:"Metadata",
long:"Metadata",
osis:"x-Meta",
type:"meta",
nt:false,
chapters:1
},{
abbr:"Intro",
short:"_Introduction_",
long:"_Introduction_",
osis:"x-Intr",
type:"meta",
nt:false,
chapters:1
},{
abbr:"Gen",
short:"က~မ္ဘာ~ဦး~ကျမ်း။",
long:"က~မ္ဘာ~ဦး~ကျမ်း။",
osis:"Gen",
type:"ot",
nt:false,
chapters:50
},{
abbr:"Exod",
short:"ထွက်~လွတ်~ရာ~ကျမ်း။",
long:"ထွက်~လွတ်~ရာ~ကျမ်း။",
osis:"Exod",
type:"ot",
nt:false,
chapters:40
},{
abbr:"Lev",
short:"လေ~ဝိ~၀တ်~ထုံး~ကျမ်း။",
long:"လေ~ဝိ~၀တ်~ထုံး~ကျမ်း။",
osis:"Lev",
type:"ot",
nt:false,
chapters:27
},{
abbr:"Num",
short:"စာ~ရင်း~တော်~ဝင်~ကျမ်း။",
long:"စာ~ရင်း~တော်~ဝင်~ကျမ်း။",
osis:"Num",
type:"ot",
nt:false,
chapters:36
},{
abbr:"Deut",
short:"ဓ~မ္မ~ထပ်~ဆင့်~ကျမ်း။",
long:"ဓ~မ္မ~ထပ်~ဆင့်~ကျမ်း။",
osis:"Deut",
type:"ot",
nt:false,
chapters:34
},{
abbr:"Josh",
short:"ယော~ရှု။",
long:"ယော~ရှု။",
osis:"Josh",
type:"ot",
nt:false,
chapters:24
},{
abbr:"Judg",
short:"တ~ရား~မင်း။",
long:"တ~ရား~မင်း။",
osis:"Judg",
type:"ot",
nt:false,
chapters:21
},{
abbr:"Ruth",
short:"ရု~သ။",
long:"ရု~သ။",
osis:"Ruth",
type:"ot",
nt:false,
chapters:4
},{
abbr:"1Sam",
short:"၁ ရှ~မွေ~လ။",
long:"၁ ရှ~မွေ~လ။",
osis:"1Sam",
type:"ot",
nt:false,
chapters:31
},{
abbr:"2Sam",
short:"၂ ရှ~မွေ~လ",
long:"၂ ရှ~မွေ~လ",
osis:"2Sam",
type:"ot",
nt:false,
chapters:24
},{
abbr:"1Kgs",
short:"၁ ဘု~ရင်~မင်း။",
long:"၁ ဘု~ရင်~မင်း။",
osis:"1Kgs",
type:"ot",
nt:false,
chapters:22
},{
abbr:"2Kgs",
short:"၂ ဘု~ရင်~မင်း။",
long:"၂ ဘု~ရင်~မင်း။",
osis:"2Kgs",
type:"ot",
nt:false,
chapters:25
},{
abbr:"1Chr",
short:"၁ ရာ~ဇ~ဝံ~သ။",
long:"၁ ရာ~ဇ~ဝံ~သ။",
osis:"1Chr",
type:"ot",
nt:false,
chapters:29
},{
abbr:"2Chr",
short:"ရာ~ဇ~ဝံ~သ~ကျမ်း~ဒု~တိ~ယ~တွဲ",
long:"ရာ~ဇ~ဝံ~သ~ကျမ်း~ဒု~တိ~ယ~တွဲ",
osis:"2Chr",
type:"ot",
nt:false,
chapters:36
},{
abbr:"Ezra",
short:"ဧ~ဇ~ရ။",
long:"ဧ~ဇ~ရ။",
osis:"Ezra",
type:"ot",
nt:false,
chapters:10
},{
abbr:"Neh",
short:"နေ~ဟ~မိ။",
long:"နေ~ဟ~မိ။",
osis:"Neh",
type:"ot",
nt:false,
chapters:13
},{
abbr:"Esth",
short:"ဧ~သ~တာ။",
long:"ဧ~သ~တာ။",
osis:"Esth",
type:"ot",
nt:false,
chapters:10
},{
abbr:"Job",
short:"ယော~ဘ။",
long:"ယော~ဘ။",
osis:"Job",
type:"ot",
nt:false,
chapters:42
},{
abbr:"Ps",
short:"ဆာ~လံ။",
long:"ဆာ~လံ။",
osis:"Ps",
type:"ot",
nt:false,
chapters:150
},{
abbr:"Prov",
short:"န~ယ~ပုံ~ပြင်~ကျမ်း။",
long:"န~ယ~ပုံ~ပြင်~ကျမ်း။",
osis:"Prov",
type:"ot",
nt:false,
chapters:31
},{
abbr:"Eccl",
short:"အာ~စ~ရိ~ယော~ဝါ~ဒ~ကျမ်း။",
long:"အာ~စ~ရိ~ယော~ဝါ~ဒ~ကျမ်း။",
osis:"Eccl",
type:"ot",
nt:false,
chapters:12
},{
abbr:"Song",
short:"ဂီ~တ~မေ~ဒ~ဏီ",
long:"ဂီ~တ~မေ~ဒ~ဏီ",
osis:"Song",
type:"ot",
nt:false,
chapters:8
},{
abbr:"Isa",
short:"ဟေ~ရှာ~ယ~ကျမ်း။",
long:"ဟေ~ရှာ~ယ~ကျမ်း။",
osis:"Isa",
type:"ot",
nt:false,
chapters:66
},{
abbr:"Jer",
short:"ယေ~ရ~မိ~ကျမ်း။",
long:"ယေ~ရ~မိ~ကျမ်း။",
osis:"Jer",
type:"ot",
nt:false,
chapters:52
},{
abbr:"Lam",
short:"ပ~ရိ~ဒေ~ဝ~ဂီ~တ~ကျမ်း။",
long:"ပ~ရိ~ဒေ~ဝ~ဂီ~တ~ကျမ်း။",
osis:"Lam",
type:"ot",
nt:false,
chapters:5
},{
abbr:"Ezek",
short:"ယေ~ဇ~ကျေ~လ~ကျမ်း။",
long:"ယေ~ဇ~ကျေ~လ~ကျမ်း။",
osis:"Ezek",
type:"ot",
nt:false,
chapters:48
},{
abbr:"Dan",
short:"ဒံ~ယေ~လ~ကျမ်း။",
long:"ဒံ~ယေ~လ~ကျမ်း။",
osis:"Dan",
type:"ot",
nt:false,
chapters:12
},{
abbr:"Hos",
short:"ဟော~ရှေ~ကျမ်း။",
long:"ဟော~ရှေ~ကျမ်း။",
osis:"Hos",
type:"ot",
nt:false,
chapters:14
},{
abbr:"Joel",
short:"ယော~လ~ကျမ်း။",
long:"ယော~လ~ကျမ်း။",
osis:"Joel",
type:"ot",
nt:false,
chapters:3
},{
abbr:"Amos",
short:"အာ~မုတ်~ကျမ်း။",
long:"အာ~မုတ်~ကျမ်း။",
osis:"Amos",
type:"ot",
nt:false,
chapters:9
},{
abbr:"Obad",
short:"ဩ~ဗ~ဒိ~ကျမ်း။",
long:"ဩ~ဗ~ဒိ~ကျမ်း။",
osis:"Obad",
type:"ot",
nt:false,
chapters:1
},{
abbr:"Jonah",
short:"ယော~န~ကျမ်း",
long:"ယော~န~ကျမ်း",
osis:"Jonah",
type:"ot",
nt:false,
chapters:4
},{
abbr:"Mic",
short:"မိ~က္ခာ~ကျမ်း။",
long:"မိ~က္ခာ~ကျမ်း။",
osis:"Mic",
type:"ot",
nt:false,
chapters:7
},{
abbr:"Nah",
short:"နာ~ဟုံ~ကျမ်း။",
long:"နာ~ဟုံ~ကျမ်း။",
osis:"Nah",
type:"ot",
nt:false,
chapters:3
},{
abbr:"Hab",
short:"ဟ~ဗ~က္ကုတ်~ကျမ်း။",
long:"ဟ~ဗ~က္ကုတ်~ကျမ်း။",
osis:"Hab",
type:"ot",
nt:false,
chapters:3
},{
abbr:"Zeph",
short:"ဇေ~ဖ~နိ~ကျမ်း။",
long:"ဇေ~ဖ~နိ~ကျမ်း။",
osis:"Zeph",
type:"ot",
nt:false,
chapters:3
},{
abbr:"Hag",
short:"ဟ~ဂ္ဂဲ~ကျမ်း။",
long:"ဟ~ဂ္ဂဲ~ကျမ်း။",
osis:"Hag",
type:"ot",
nt:false,
chapters:2
},{
abbr:"Zech",
short:"ဇာ~ခ~ရိ~ကျမ်း။",
long:"ဇာ~ခ~ရိ~ကျမ်း။",
osis:"Zech",
type:"ot",
nt:false,
chapters:14
},{
abbr:"Mal",
short:"မာ~လ~ခိ~ကျမ်း။",
long:"မာ~လ~ခိ~ကျမ်း။",
osis:"Mal",
type:"ot",
nt:false,
chapters:4
},{
abbr:"Matt",
short:"ရှင်~မဿဲ။",
long:"ရှင်~မဿဲ။",
osis:"Matt",
type:"nt",
nt:true,
chapters:28
},{
abbr:"Mark",
short:"ရှင်~မာ~ကု",
long:"ရှင်~မာ~ကု",
osis:"Mark",
type:"nt",
nt:true,
chapters:16
},{
abbr:"Luke",
short:"ရှင်~လု~ကာ",
long:"ရှင်~လု~ကာ",
osis:"Luke",
type:"nt",
nt:true,
chapters:24
},{
abbr:"John",
short:"ရှင်ယောဟန်",
long:"ရှင်ယောဟန်",
osis:"John",
type:"nt",
nt:true,
chapters:21
},{
abbr:"Acts",
short:"တ~မန်~တော်~ဝ~တ္ထု။",
long:"တ~မန်~တော်~ဝ~တ္ထု။",
osis:"Acts",
type:"nt",
nt:true,
chapters:28
},{
abbr:"Rom",
short:"ရော~မ~ဩ~ဝါ~ဒ~ကျမ်း။",
long:"ရော~မ~ဩ~ဝါ~ဒ~ကျမ်း။",
osis:"Rom",
type:"nt",
nt:true,
chapters:16
},{
abbr:"1Cor",
short:"၁ ကော~ရိ~န္သု~ဩ~ဝါ~ဒ~ကျမ်း",
long:"၁ ကော~ရိ~န္သု~ဩ~ဝါ~ဒ~ကျမ်း",
osis:"1Cor",
type:"nt",
nt:true,
chapters:16
},{
abbr:"2Cor",
short:"၂ ကော~ရိ~န္သု~ဩ~ဝါ~ဒ~ကျမ်း။",
long:"၂ ကော~ရိ~န္သု~ဩ~ဝါ~ဒ~ကျမ်း။",
osis:"2Cor",
type:"nt",
nt:true,
chapters:13
},{
abbr:"Gal",
short:"ဂ~လာ~တိ~ဩ~ဝါ~ဒ~ကျမ်း။",
long:"ဂ~လာ~တိ~ဩ~ဝါ~ဒ~ကျမ်း။",
osis:"Gal",
type:"nt",
nt:true,
chapters:6
},{
abbr:"Eph",
short:"ဧ~ဖက်~ဩ~ဝါ~ဒ~ကျမ်း။",
long:"ဧ~ဖက်~ဩ~ဝါ~ဒ~ကျမ်း။",
osis:"Eph",
type:"nt",
nt:true,
chapters:6
},{
abbr:"Phil",
short:"ဖိ~လိ~ပ္ပိ~ဩ~ဝါ~ဒ~ကျမ်း။",
long:"ဖိ~လိ~ပ္ပိ~ဩ~ဝါ~ဒ~ကျမ်း။",
osis:"Phil",
type:"nt",
nt:true,
chapters:4
},{
abbr:"Col",
short:"ကော~လော~သဲ~ဩ~ဝါ~ဒ~ကျမ်း။",
long:"ကော~လော~သဲ~ဩ~ဝါ~ဒ~ကျမ်း။",
osis:"Col",
type:"nt",
nt:true,
chapters:4
},{
abbr:"1Thess",
short:"သက်~သာ~လော~နိတ်~ဩ~ဝါ~ဒ~ကျမ်း ပ~ဌ~မ~စောင်။",
long:"သက်~သာ~လော~နိတ်~ဩ~ဝါ~ဒ~ကျမ်း ပ~ဌ~မ~စောင်။",
osis:"1Thess",
type:"nt",
nt:true,
chapters:5
},{
abbr:"2Thess",
short:"သက်~သာ~လော~နိတ်~ဩ~ဝါ~ဒ~ကျမ်း ဒု~တိ~ယ~စောင်။",
long:"သက်~သာ~လော~နိတ်~ဩ~ဝါ~ဒ~ကျမ်း ဒု~တိ~ယ~စောင်။",
osis:"2Thess",
type:"nt",
nt:true,
chapters:3
},{
abbr:"1Tim",
short:"၁ တိ~မော~သေ။",
long:"၁ တိ~မော~သေ။",
osis:"1Tim",
type:"nt",
nt:true,
chapters:6
},{
abbr:"2Tim",
short:"တိ~မော~သေ~ဩ~ဝါ~ဒကျမ်း ဒု~တိ~ယ~စောင်။",
long:"တိ~မော~သေ~ဩ~ဝါ~ဒကျမ်း ဒု~တိ~ယ~စောင်။",
osis:"2Tim",
type:"nt",
nt:true,
chapters:4
},{
abbr:"Titus",
short:"﻿တိ~တု~ဩ~ဝါ~ဒ~ကျမ်း။",
long:"﻿တိ~တု~ဩ~ဝါ~ဒ~ကျမ်း။",
osis:"Titus",
type:"nt",
nt:true,
chapters:3
},{
abbr:"Phlm",
short:"ဖိ~လေ~မုန်~ဩ~ဝါ~ဒ~ကျမ်း။",
long:"ဖိ~လေ~မုန်~ဩ~ဝါ~ဒ~ကျမ်း။",
osis:"Phlm",
type:"nt",
nt:true,
chapters:1
},{
abbr:"Heb",
short:"ဟေ~ဗြဲ~ဩ~ဝါ~ဒ~ကျမ်း။",
long:"ဟေ~ဗြဲ~ဩ~ဝါ~ဒ~ကျမ်း။",
osis:"Heb",
type:"nt",
nt:true,
chapters:13
},{
abbr:"Jas",
short:"ယာ~ကုပ်~ဩ~ဝါ~ဒ~ကျမ်း။",
long:"ယာ~ကုပ်~ဩ~ဝါ~ဒ~ကျမ်း။",
osis:"Jas",
type:"nt",
nt:true,
chapters:5
},{
abbr:"1Pet",
short:"ပေ~တ~ရု~ဩ~ဝါ~ဒ~ကျမ်း~ပ~ဌ~မ~စောင်။",
long:"ပေ~တ~ရု~ဩ~ဝါ~ဒ~ကျမ်း~ပ~ဌ~မ~စောင်။",
osis:"1Pet",
type:"nt",
nt:true,
chapters:5
},{
abbr:"2Pet",
short:"၂ ပေ~တ~ရု။",
long:"၂ ပေ~တ~ရု။",
osis:"2Pet",
type:"nt",
nt:true,
chapters:3
},{
abbr:"1John",
short:"ယော~ဟန်၏~ဩ~ဝါ~ဒ~ကျမ်း~ပ~ဌ~မ~စောင်။",
long:"ယော~ဟန်၏~ဩ~ဝါ~ဒ~ကျမ်း~ပ~ဌ~မ~စောင်။",
osis:"1John",
type:"nt",
nt:true,
chapters:5
},{
abbr:"2John",
short:"၂ ﻿ယော~ဟန်။",
long:"၂ ﻿ယော~ဟန်။",
osis:"2John",
type:"nt",
nt:true,
chapters:1
},{
abbr:"3John",
short:"၃ ယော~ဟန်။",
long:"၃ ယော~ဟန်။",
osis:"3John",
type:"nt",
nt:true,
chapters:1
},{
abbr:"Jude",
short:"ယု~ဒ~ဩ~ဝါ~ဒ~ကျမ်း။",
long:"ယု~ဒ~ဩ~ဝါ~ဒ~ကျမ်း။",
osis:"Jude",
type:"nt",
nt:true,
chapters:1
},{
abbr:"Rev",
short:"ဗျာ~ဒိတ်~တော်~ကျမ်း။",
long:"ဗျာ~ဒိတ်~တော်~ကျမ်း။",
osis:"Rev",
type:"nt",
nt:true,
chapters:22
}];
